-- This file is used for linting .tld files with typedlua

require "http.bit"
require "http.client"
require "http.connection_common"
require "http.cookie"
require "http.h1_connection"
require "http.h1_reason_phrases"
require "http.h1_stream"
require "http.h2_connection"
require "http.h2_error"
require "http.h2_stream"
require "http.headers"
require "http.hpack"
require "http.hsts"
require "http.proxies"
require "http.request"
require "http.server"
require "http.socks"
require "http.stream_common"
require "http.tls"
require "http.util"
require "http.version"
require "http.websocket"
require "http.zlib"
require "http.compat.prosody"
require "http.compat.socket"
